### ISSUE TITLE
Issue with PHP-Switcher

### ISSUE THREAD

**Issue by mhanon** [mlocati/powershell-phpmanager#117]
Here is an image of the issue. I'm following the example in the docs almost exactly. Please let me know if you need additional information. I'm using Windows 10, PowerShell running as admin.

![image](https://github.com/mlocati/powershell-phpmanager/assets/118755729/10cb8136-1d71-4b6e-9ae9-a55b7fb10fb0)

It only works if I force it.
![image](https://github.com/mlocati/powershell-phpmanager/assets/118755729/704dae18-26c2-49e6-ab40-8ebb4ef15415)

**Comment by mlocati** [comment]
As described by the error message, the problem is that you have these directories in your PATH environment variable:

- `C:\PHP\PHP7.3.7`
- `C:\php\PHP8.3`

In order to avoid problems, you should remove them from the PATH environment variable.

Only the directory managed by PHP Switcher (`C:\PHP\PHP`) should be listed in the PATH environment variable.

**Comment by mhanon** [comment]
Sorry about that, the error wording is a little confusing.

**Comment by mlocati** [comment]
Can you suggest a clearer error message?

**Comment by mlocati** [comment]
The part of the error message that I change is the following one:

```
PHP is currently available in the following directories:
- C:\PHP\PHP7.3.7
- C:\php\PHP8.3
PHP Switcher is meant to have PHP in PATH only as C:\PHP\PHP
You can override this behavior by calling Switch-Php with the -Force flag.
```

The rest of the error message is built automatically by PowerShell.
