### ISSUE TITLE
Timing of version upgrades?

### ISSUE THREAD

**Issue by schmidtl4** [mlocati/powershell-phpmanager#30]
Running PHP 7.2.18 and just ran the `Update-Php` command.  The response was "False" - presumably indicating no upgrade available?   However https://windows.php.net/download/ has the latest version as 7.3.5 (admittedly released yesterday).  What is the timing of the PhpManager updates relative to when versions are released?

**Comment by mlocati** [comment]
What's the output of `Update-Php` when you use the `-Verbose` option?

**Comment by schmidtl4** [comment]
VERBOSE: No new version available (latest version is 7.2.18)

**Comment by mlocati** [comment]
Up, I just read your question kore carefully: you would like to upgrade from PHP 7.2 to PHP 7.3.

While changing the patch version (eg from `7.2.17` to `7.2.18`) is usually safe, changing the minor version (eg from `7.2.whatever` to `7.3.whatever`) may break some code. Furthermore, additional PHP extensions must be upgraded as well.
For these reasons, PhpManager doesn't allow you that with the `Update-Php` command.

In order to upgrade from 7.2 to 7.3 you can use the `Install-Php` command with the `-Force` flag (if you don't specify the `-InitialPhpIni` flag, the existing `php.ini` file won't be overwritten).

**Comment by schmidtl4** [comment]
Ah - good to know.  Thanks for the explanation.
