### ISSUE TITLE
Fix Imagick on PHP 8.0

### ISSUE THREAD

**Issue by shivammathur** [mlocati/powershell-phpmanager#82]
Imagemagick vs16 is not there on https://windows.php.net/downloads/pecl/deps. instead, PHP 8.0 Imagick builds have Imagemagick libraries in the [extension archive](https://windows.php.net/downloads/pecl/releases/imagick/3.5.1/php_imagick-3.5.1-8.0-nts-vs16-x64.zip).

So, `Install-PhpExtensionPrerequisite` should use the extension archive to put the dependencies in `InstallPath` on PHP 8.0.

**Comment by mlocati** [comment]
`Install-PhpExtensionPrerequisite` is meant to fetch additional files.

Since users usually install php extensions by using `Install-PhpExtension` I updated its code - see #83

If you don't install `imagick` with `Install-PhpExtension` you have to add those additional DLL files to a directory listed in in the `PATH` environment variable (or in the directory where `php.exe` resides) manually.

**Comment by shivammathur** [comment]
@mlocati 

Thanks for fixing this quickly.

setup-php uses `InstallPath` parameter in `Install-PhpExtensionPrerequisite` to install the dependencies to a directory in PATH which can be cached. 

If a similar parameter can be added to `Install-PhpExtension` that if present would copy the `$additionalFiles` to the input directory instead of the PHP path, it would be great.

**Comment by mlocati** [comment]
@shivammathur something like #86 would work for you?

**Comment by shivammathur** [comment]
@mlocati Yes, that would be perfect.

**Comment by mlocati** [comment]
@shivammathur the new version (1.25.4) implementing this is now available
